version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command: "node index.js"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes_from:
      - mongo_data
  mongo_data:
    image: tianon/true
    volumes:
      - /data/db
    